services:
  reviewer-api:
    image: jaylordibe/laravel-php
    container_name: reviewer-api
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - reviewer-network
  reviewer-db:
    image: mysql:8.0.25
    container_name: reviewer-db
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "3396:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      - reviewer-network
  reviewer-db-gui-admin:
    image: phpmyadmin/phpmyadmin
    container_name: reviewer-db-gui-admin
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "8091:80"
    environment:
      PMA_HOST: reviewer-db
      UPLOAD_LIMIT: 300M
    networks:
      - reviewer-network
  reviewer-db-test:
    image: mysql:8.0.25
    container_name: reviewer-db-test
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "3397:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_DATABASE}
      MYSQL_USER: ${TEST_DB_USERNAME}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - ./docker/database/test-data:/var/lib/mysql
    networks:
      - reviewer-network
  reviewer-db-test-gui-admin:
    image: phpmyadmin/phpmyadmin
    container_name: reviewer-db-test-gui-admin
    restart: unless-stopped
    tty: true
    platform: linux/x86_64
    ports:
      - "8092:80"
    environment:
      PMA_HOST: reviewer-db-test
      UPLOAD_LIMIT: 300M
    networks:
      - reviewer-network
networks:
  reviewer-network:
    driver: bridge
